### ISSUE TITLE
Type dropdown menu issue to create new Container on 2.6.1

### ISSUE THREAD

**Issue by arielzn** [collec-science/collec-science#585]
Hello, 

On version 2.6.1 the "Create / Edit a container" form seems to have an issue, the dropdown menu for "Type" after correctly selecting a "Family" is showing nothing.

i tested to downgrade to 2.6.0 (keeping the exact same db)  and there the dropdown works correctly

**Comment by arielzn** [comment]
i don't see any errors logged on the server neither on the console.

i'm testing a deployment based on containers by the way, but with the exact same install approach for collec-science (same php, apache, etc..)  i get the result i mention, on 2.6.0 it works fine but not on 2.6.1 

for when are you planning the 2.7.0 release ?

**Comment by equinton** [comment]
Have you checked if the database is the same in all containers? You can check the contents of the table with this query (Objects > SQL requests): 
SELECT * from container_type

I hope to release the next version before july. The version is ready, but I need to prepare the scripts to update and  create the database. And I would like to transfert the repository to collec-science/collec-science.

**Comment by arielzn** [comment]
The database is exactly the same as I have only a single postgres container with the db. 

I'm changing only which  collec-science container connects to it,  either 2.6.0 or 2.6.1.

**Comment by equinton** [comment]
I've been experiencing some weirdness with Firefox. Have you tested it on another browser or from another machine?

**Comment by equinton** [comment]
The problem can happen if the cache is not cleared between two versions.

**Comment by arielzn** [comment]
hello, sorry about not reacting before, busy with some other things.

I'll take a detaild look again these days and let your know.

so this issue could be present even on your newer versions ?

**Comment by equinton** [comment]
Hello,
I have never been able to reproduce your problem, and no one else has reported it to me.
However, I have experienced some strange behaviors: truncated list of samples, for example, which were solved by deleting the cookies and cache for the application in the browser (Firefox in this case).
I am currently preparing a corrective version of version 2.8, due to bugs discovered after the production release. I don't have many testers now to check that everything is ok before delivering the new versions.
Eric.
